[build]
  command = "npm run build"
  publish = "build/"

[functions]
  directory = "src/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  targetPort = 5173
  
[[plugins]]
package = 'netlify-plugin-contextual-env'
