[build]
  command = "npm run build"
  publish = "build/"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "src/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "https://ona.com"
  status = 302
  force = true

